server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ""
    initialize: false
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
    hibernate:
      ddl-auto: validate


flyway:
  enabled: true
  baseline-on-migrate: true
