spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ""
    sql-script-encoding: UTF-8
    initialize: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    hibernate:
      ddl-auto: validate

flyway:
  enabled: true
  initOnMigrate: true